import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { FaArrowLeft, FaArrowRight } from 'react-icons/fa';
import { blogPosts } from '@/data/blog-posts';
import { siteConfig } from '@/config/site';
interface Props { params: Promise<{slug:string}> }
export async function generateStaticParams(){return blogPosts.filter(p=>p.published).map(p=>({slug:p.slug}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const post=blogPosts.find(p=>p.slug===slug&&p.published);return post?{title:{absolute:post.metaTitle||`${post.title} | ${siteConfig.name}`},description:post.metaDescription||post.excerpt,alternates:{canonical:`/blog/${post.slug}`},openGraph:{title:post.title,description:post.excerpt,url:`/blog/${post.slug}`,type:'article',publishedTime:post.date,authors:[post.author],images:[{url:'/Newimages/accident/damaged-front.jpg',width:1800,height:1200,alt:post.title}]}}:{title:'Blog Yazısı Bulunamadı'};}
export default async function BlogPostPage({params}:Props){const {slug}=await params;const post=blogPosts.find(p=>p.slug===slug&&p.published);if(!post)notFound();const related=blogPosts.filter(p=>p.published&&p.id!==post.id&&p.category===post.category).slice(0,3);const url=`${siteConfig.url}/blog/${post.slug}`;const articleSchema={'@context':'https://schema.org','@type':'Article',headline:post.title,description:post.metaDescription||post.excerpt,datePublished:post.date,dateModified:post.date,mainEntityOfPage:{'@type':'WebPage','@id':url},author:{'@type':'Organization',name:post.author},publisher:{'@id':`${siteConfig.url}/#organization`},image:[`${siteConfig.url}/Newimages/accident/damaged-front.jpg`],inLanguage:'tr-TR'};return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(articleSchema)}}/><header className="border-b border-line bg-surface"><div className="site-container py-12 sm:py-20"><nav aria-label="Sayfa yolu" className="text-sm text-muted"><Link href="/">Ana Sayfa</Link><span className="px-2">/</span><Link href="/blog">Blog</Link></nav><p className="eyebrow mt-10">{post.category}</p><h1 className="display mt-4 max-w-4xl text-4xl leading-tight sm:text-6xl">{post.title}</h1><p className="mt-6 text-sm text-muted">{post.date} · {post.author}</p></div></header><main className="site-container section-space"><article className="prose mx-auto" dangerouslySetInnerHTML={{__html:post.content}}/><div className="mx-auto mt-14 flex max-w-[820px] justify-between border-t border-line pt-8"><Link href="/blog" className="inline-flex items-center gap-2 font-bold"><FaArrowLeft/>Tüm yazılar</Link><Link href="/#arac-sat" className="button-primary">Teklif Al <FaArrowRight/></Link></div>{related.length>0&&<section className="mx-auto mt-20 max-w-[1120px]"><h2 className="display text-3xl">İlgili Yazılar</h2><div className="mt-6 grid gap-4 md:grid-cols-3">{related.map(item=><Link key={item.id} href={`/blog/${item.slug}`} className="border border-line bg-surface p-5"><p className="eyebrow">{item.category}</p><h3 className="display mt-3 text-lg">{item.title}</h3></Link>)}</div></section>}</main></>;}
