import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { FaArrowRight } from 'react-icons/fa';
import { services } from '@/data/services';
import { siteConfig } from '@/config/site';
import { getServiceImage } from '@/data/media';
export const metadata: Metadata = { title: { absolute: `Hizmetlerimiz | ${siteConfig.name}` }, description: 'Kazalı, hasarlı, pert ve hurda araç alımı ile ekspertiz, trafiğe çıkış ve takas hizmetleri hakkında bilgi alın.', keywords: ['araç alım hizmetleri', 'ekspertiz', 'trafiğe çıkış', 'araç takas'], alternates: { canonical: '/hizmetler' }, openGraph: { url: '/hizmetler', images: [{ url: getServiceImage('hasarli-arac-alim'), width: 1600, height: 1200, alt: 'Araban Nakit hizmetleri' }] } };
export default function ServicesPage(){const list=services.filter(s=>s.published);return <><section className="border-b border-line bg-surface"><div className="site-container py-16 sm:py-24"><p className="eyebrow">ARABAN NAKİT HİZMETLERİ</p><h1 className="display mt-5 max-w-3xl text-5xl leading-tight sm:text-7xl">Aracınızın durumuna göre doğru çözüm.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted">Kazalı, hasarlı, pert ve hurda araçlar için hızlı değerlendirme ve profesyonel süreç yönetimi.</p></div></section><section className="site-container section-space"><div className="grid gap-5 md:grid-cols-2">{list.map(service=><Link key={service.id} href={`/hizmetler/${service.slug}`} className="group grid overflow-hidden border border-line bg-surface sm:grid-cols-2"><div className="relative aspect-[4/3] bg-soft"><Image src={getServiceImage(service.slug)} alt={service.title} fill sizes="(max-width:768px) 100vw,50vw" className="object-cover transition duration-300 group-hover:scale-[1.03]"/></div><div className="flex flex-col p-6"><h2 className="display text-2xl">{service.title}</h2><p className="mt-4 text-sm leading-6 text-muted">{service.shortDescription}</p><span className="mt-auto pt-8 inline-flex items-center gap-2 text-sm font-bold">Detayları incele <FaArrowRight className="transition group-hover:translate-x-1"/></span></div></Link>)}</div></section><section className="border-y border-line bg-surface"><div className="site-container section-space grid gap-8 lg:grid-cols-3"><div><p className="eyebrow">BİLGİLİ SATIŞ</p><h2 className="display mt-4 text-3xl">Aracınızın durumunu paylaşın.</h2><p className="mt-4 leading-7 text-muted">Fotoğraflar, hasar bilgisi ve mevcut belgeler değerlendirme sürecini hızlandırmaya yardımcı olur.</p></div><div><h2 className="display text-xl">Teklif süreci</h2><p className="mt-4 leading-7 text-muted">Bilgi paylaşımı, inceleme, teklif ve noter işlemleri; her adımda ne olacağını bilerek ilerlersiniz.</p></div><div><h2 className="display text-xl">Doğru hizmete ulaşın</h2><p className="mt-4 leading-7 text-muted">Aracın durumu hangi hizmetin uygun olduğunu belirler. Her hizmet sayfasında kapsam, süreç ve sık sorulan sorular yer alır.</p></div></div></section></>;}
